#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# Restarting nginx
sudo service nginx restart
echo -e "\nCompleted.\n"
