#!/usr/bin/env bash
# install load balancer


echo -e "wait updating with some checks...\n"

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy #install haproxy

echo -e "\nwait,setting up some stuff.\n"

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend globallaab-tech-frontend
    bind *:80
    default_backend globallaab-tech-backend

backend globallaab-tech-backend
    balance roundrobin
    server 422684-web-01 35.175.128.201:80 check
    server 422684-web-02 100.25.144.3:80 check
"

echo "$server_configuring" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enabling the haproxy
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "is configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
