#!/usr/bin/env bash
#Creating a script thatprints string 10tmes then hi on the 10th time

x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
